Create NumPy arrays from scratch and from data & Perform:

*Basic ops: +, *, .reshape(), .mean(), .std()

*Boolean masking

*Matrix multiplication 

*Broadcasting (np.array([1,2,3]) + 5)

*np.where(), np.any(), np.all() usage

*Compare memory/time between NumPy arrays and Python lists

In [3]:
import numpy as np

In [4]:
# nnumpy array for manipulation (1-d)
arr_1= np.array([1,2,3])
arr_2= np.array([6,8,4])
# add
add= arr_1+arr_2
print('sum:',add)
#multiply
mul= arr_1* arr_2
print('product:',mul)
# reshape
arr_3= np.concatenate((arr_1, arr_2), axis=0)
print('original array',arr_3)
arr_4= arr_3.reshape(2,3)
print('reshaped array:',arr_4)
#mean
mean=arr_3.mean()
print('mean:', mean)
stand_dev= arr_3.std().round(2)
print('stadard deviation:', stand_dev)


sum: [ 7 10  7]
product: [ 6 16 12]
original array [1 2 3 6 8 4]
reshaped array: [[1 2 3]
 [6 8 4]]
mean: 4.0
stadard deviation: 2.38


In [5]:
#2-d
arr_2d= np.array([[2,4,3,8,12,45], [23,56,12,63,11,34]])
arr_2d1= np.array([[6,72,12,21,4,3],[23,4,5,12,53,23]])

#reshape
arr_3d=arr_2d.reshape(1,3,4)
print('reshapes array:',arr_3d.reshape(1,3,4))
#add
print('sum', arr_2d+ arr_2d1)
#product
print('product:', arr_2d *arr_2d1)
#mean
print('mean:', arr_2d.mean())
#standard deviation
print('standard deviation:', arr_2d1.std().round(2))


reshapes array: [[[ 2  4  3  8]
  [12 45 23 56]
  [12 63 11 34]]]
sum [[ 8 76 15 29 16 48]
 [46 60 17 75 64 57]]
product: [[ 12 288  36 168  48 135]
 [529 224  60 756 583 782]]
mean: 22.75
standard deviation: 20.74


In [11]:
# 3-d (broadcasting)
arr_3d1= np.random.randint(1,50 , size= (1,3,4))
print(arr_3d1,'\n')
#add 
print('sum:', arr_3d+ arr_3d1 ,'\n')
# product
arr_1d= np.array([2,4,3,7])
print('product:', arr_3d1*arr_1d, '\n') #here broadcasting works by multiplying two arrays of different sizes and dimension
#add using broadcasting
print('add using broadcasting:', arr_3d+ arr_1d)
print('add using broadcasting:', arr_3d+ arr_3d1)

[[[ 2 16 31 32]
  [10 13 34 26]
  [22  6 46 13]]] 

sum: [[[ 4 20 34 40]
  [22 58 57 82]
  [34 69 57 47]]] 

product: [[[  4  64  93 224]
  [ 20  52 102 182]
  [ 44  24 138  91]]] 

add using broadcasting: [[[ 4  8  6 15]
  [14 49 26 63]
  [14 67 14 41]]]
add using broadcasting: [[[ 4 20 34 40]
  [22 58 57 82]
  [34 69 57 47]]]


broadcasting only works when shape of the rows are same of two arrays like [1,2,3] and [[2,5,3],[4,6,4]]

In [7]:
# boolean Masking
arr_b= np.random.randint(5,23, size=(2,3))
print(arr_b)
mask= arr_b > 12
mask #masked values i true and false
arr_b[mask]

[[ 8 19  7]
 [13 17 20]]


array([19, 13, 17, 20], dtype=int32)

in boolean masking we are passing a condition, and if it comestrue it will show every true value

In [8]:
# matrix multiplication 
arr_m=np.array([[2,43,5], [23,56,12],[4,3,2]])
arr_n= np.random.randint(1,100, size= (3,3))
arr_n
print('matrix multiplication: ', np.dot(arr_m ,arr_n))
arr_t= np.array([[1],[5],[23]])
print('matrix mul on (3*3) and (1*3)', arr_m@ arr_t)

matrix multiplication:  [[1724 2808 1765]
 [3246 5676 3974]
 [ 344  594  477]]
matrix mul on (3*3) and (1*3) [[332]
 [579]
 [ 65]]


In [10]:
#Broadcasting (np.array([1,2,3]) + 5)
arr_b= np.array([1,2,3])
print('the sum :', arr_b + 5)

the sum : [6 7 8]


broadcasting extends the smaller array to be manipulated or aggregted with big size array 

In [46]:
#Compare memory/time between NumPy arrays and Python lists
# sum on python lists
l1= [2,4,5]
l2=[4,6,32]
#for x,y in zip(l1,l2):   # zip pair the elements of l1 to elements of l2 like ([2,4], [4,6], [5,32]) as a tuple, x takes values from a and y takes values from b
res=[ x+y for x,y in zip(l1,l2)]
print('the sum of two lists :', res)

# numpy sum 
n1= np.array([2,4,3])
n2= np.array([5,7,21])
print('the sum of two arrays (np):', np.add(n1,n2) )
# evaluation of efficiency
from timeit import timeit
time_list= timeit('''l1= [2,4,5]
l2=[4,6,32]
res=[ x+y for x,y in zip(l1,l2)]

''', number=10000)
print('time taken by sum of two lists :',time_list)
time_array=timeit(''' 
import numpy as np
n1= np.array([2,4,3])
n2= np.array([5,7,21])
sumnp= n1+n2
''', number= 10000)
print('time taken by sum of two np arrays:', time_array )


the sum of two lists : [6, 10, 37]
the sum of two arrays (np): [ 7 11 24]
time taken by sum of two lists : 0.007679800000914838
time taken by sum of two np arrays: 0.09772760000123526


zip() pair the elements of l1 to elements of l2 like ([2,4], [4,6], [5,32]) as a tuple, x takes values from a and y takes values from b.
here we have taken two lists and add them, and same goes for np arrays, now we are evaluating the time taken by both addition functions by using timeit(). in timeit we enclose the whole code in triple qoutes to make that python code into a single multiline string.

In [61]:
#np.where(), np.any(), np.all() usage
ar= np.random.randint(1,10, 5)
print(ar)
ar1= np.random.randint(1,20,5)
print(ar1)
print('less than 4 will be *',np.where(ar<4, '*', 'o'))# elements less than 4 will be * and more than 4 will be o
print(np.where(ar>7, ar, ar1)) # elements if greater than 7 they will return all values of ar and then will get values from ar1

[1 6 5 2 4]
[ 5  7  9  9 11]
less than 4 will be * ['*' 'o' 'o' '*' 'o']
[ 5  7  9  9 11]


np.where() is a conditional function which takes a condition and x, y where x contains truth values and y contains false values

In [67]:
# np.any()
wr= np.array([0,1,1,2,3,0])
print(np.any(wr<1)) # np.any() gives a true if any of the element is conditionally true 
wr1= np.array([0,1,4,1])
print(np.all(wr>0))  # np.all() gives true value only if all  the values are conditionally true 
wrr= np.array([[[2,3,4],[3,4,5],[7,2,6]]])
print(np.any(wrr<6, axis=1))
print(np.all(wrr>3, axis= 1))

True
False
[[ True  True  True]]
[[False False  True]]


np.any() gives a true if any of the element is conditionally true, np.all() gives true value only if all  the values are conditionally true.