Create NumPy arrays from scratch and from data & Perform:

#Basic ops: +, *, .reshape(), .mean(), .std()

#Boolean masking

#Matrix multiplication 

In [2]:
import numpy as np

In [23]:
# nnumpy array for manipulation (1-d)
arr_1= np.array([1,2,3])
arr_2= np.array([6,8,4])
# add
add= arr_1+arr_2
print('sum:',add)
#multiply
mul= arr_1* arr_2
print('product:',mul)
# reshape
arr_3= np.concatenate((arr_1, arr_2), axis=0)
print('original array',arr_3)
arr_4= arr_3.reshape(2,3)
print('reshaped array:',arr_4)
#mean
mean=arr_3.mean()
print('mean:', mean)
stand_dev= arr_3.std().round(2)
print('stadard deviation:', stand_dev)


sum: [ 7 10  7]
product: [ 6 16 12]
original array [1 2 3 6 8 4]
reshaped array: [[1 2 3]
 [6 8 4]]
mean: 4.0
stadard deviation: 2.38


In [55]:
#2-d
arr_2d= np.array([[2,4,3,8,12,45], [23,56,12,63,11,34]])
arr_2d1= np.array([[6,72,12,21,4,3],[23,4,5,12,53,23]])

#reshape
arr_3d=arr_2d.reshape(1,3,4)
print('reshapes array:',arr_3d.reshape(1,3,4))
#add
print('sum', arr_2d+ arr_2d1)
#product
print('product:', arr_2d *arr_2d1)
#mean
print('mean:', arr_2d.mean())
#standard deviation
print('standard deviation:', arr_2d1.std().round(2))


reshapes array: [[[ 2  4  3  8]
  [12 45 23 56]
  [12 63 11 34]]]
sum [[ 8 76 15 29 16 48]
 [46 60 17 75 64 57]]
product: [[ 12 288  36 168  48 135]
 [529 224  60 756 583 782]]
mean: 22.75
standard deviation: 20.74


In [62]:
# 3-d (broadcasting)
arr_3d1= np.random.randint(1,50 , size= (1,3,4))
print(arr_3d1,'\n')
#add 
print('sum:', arr_3d+ arr_3d1 ,'\n')
# product
arr_1d= np.array([2,4,3,7])
print('product:', arr_3d1*arr_1d, '\n') #here broadcasting works by multiplying two arrays of different sizes and dimension
#add using broadcasting
print('add using broadcasting:', arr_3d+ arr_1d)

[[[32 12 25 28]
  [46 29  5 26]
  [20 26  3 29]]] 

sum: [[[34 16 28 36]
  [58 74 28 82]
  [32 89 14 63]]] 

product: [[[ 64  48  75 196]
  [ 92 116  15 182]
  [ 40 104   9 203]]] 

add using broadcasting: [[[ 4  8  6 15]
  [14 49 26 63]
  [14 67 14 41]]]


broadcasting only works when shape of the rows are same of two arrays like [1,2,3] and [[2,5,3],[4,6,4]]

In [74]:
# boolean Masking
arr_b= np.random.randint(5,23, size=(2,3))
print(arr_b)
mask= arr_b > 12
mask #masked values i true and false
arr_b[mask]

[[21 12  9]
 [12 16 11]]


array([21, 16], dtype=int32)

In [86]:
# matrix multiplication 
arr_m=np.array([[2,43,5], [23,56,12],[4,3,2]])
arr_n= np.random.randint(1,100, size= (3,3))
arr_n
print('matrix multiplication: ', np.dot(arr_m ,arr_n))
arr_t= np.array([[1],[5],[23]])
print('matrix mul on (3*3) and (1*3)', arr_m@ arr_t)

matrix multiplication:  [[2458 2105 3577]
 [4675 3706 4827]
 [ 467  387  298]]
matrix mul on (3*3) and (1*3) [[332]
 [579]
 [ 65]]
